variables:
  UV_LINK_MODE: copy

stages:
  - test
  - deploy

image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim

uv-install:
  variables:
    UV_CACHE_DIR: .uv-cache
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  script:
    - uv cache prune --ci


pre-commit-checks:
  stage: test
  interruptible: true
  before_script:
    - python -V
    - uv -V
  script:
    - uv run pre-commit run --all-files --color always


docker-build:
  image: docker:28.0.1-cli
  stage: deploy
  services:
    - docker:28.0.1-dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t --pull "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
