# Configuration for pre-commit hooks (see https://pre-commit.com/).
# Eventually the hooks described here will be run as tests before merging each PR.

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.6
    hooks:
      - id: uv-lock
      - id: uv-export


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        types_or: [python, pyi]


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--strict, --local-partial-types, --warn-unreachable]
        additional_dependencies:
          - polars
          - types-pyyaml
          - pydantic-settings
          - types-psutil
          - docxtpl


  - repo: local
    hooks:
      - id: print_actual_packages
        name: print_actual_packages
        entry: 'uv tree --outdated --depth=1 --color=always'
        language: system
        pass_filenames: false
        verbose: true
