version: 1
disable_existing_loggers: False

formatters:
  simpleFormatter:
    format: "%(asctime)s - %(levelname)s - %(message)s"
  detailedFormatter:
    format: "%(asctime)s - %(levelname)s - %(module)s - %(lineno)s - %(funcName)s - %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: WARNING
    formatter: simpleFormatter
    stream: ext://sys.stdout

  fileHandler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailedFormatter
    filename: logs/logger.log
    mode: a
    maxBytes: 5242880  # 5 MB
    backupCount: 5 # Keep up to 5 backup files
    encoding: utf8

root:
  level: DEBUG
  handlers: [consoleHandler, fileHandler]
